name: Build Docker images, push to Docker Hub

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to OVHCloud Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ${{ secrets.OVHCLOUD_REGISTRY }}
          username: ${{ secrets.OVHCLOUD_REGISTRY_USERNAME }}
          password: ${{ secrets.OVHCLOUD_REGISTRY_PASSWORD }}
      - 
        name: Get the tag
        id: get_tag_name
        # set the tag without the "v" prefix
        # firstString="I love Suzi and Marry"
        # secondString="Sara"
        # echo "${firstString/Suzi/"$secondString"}"    
        run: echo "TAG_NAME=$(echo ${{github.ref_name}} | sed 's/^v//')" >> $GITHUB_ENV
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ secrets.OVHCLOUD_REGISTRY }}/prod/socialis:latest
            ${{ secrets.OVHCLOUD_REGISTRY }}/prod/socialis:${{ env.TAG_NAME }}
      - 
        name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_REPOSITORY: ${{ github.repository_owner }}/socialis